default:
  export_data: true
  export_viz: true
  dir_data: "data"
  dir_viz: "figs"
  
  # path_png_map_lmp_rtm_raw: "data-raw/rtmLmp.png"
  path_png_map_spp_rtm_raw: "data-raw/rtmSpp.png"
  path_png_map_spp_dam_raw: "data-raw/damSpp.png"
  path_png_legend_raw: "data-raw/rtmLmpLegend.png"
  
  path_kml_raw: "data-raw/rtmLmp.kml"
  path_kml_pnt: "data/kml_pnt.csv"
  path_color: "data/color.csv"
  
  # path_lmp_pnt: "data/lmp_pnt.csv"
  path_spp_rtm_raw: "data-raw/cdr.00012301.0000000000000000.20181113.064703.SPPHLZNP6905_20181113_0645.csv"
  path_spp_dam_raw: "data-raw/cdr.00012331.0000000000000000.20181112.123220.DAMSPNP4190.csv"
  
  # path_pnt: "data/pnt.csv"
  path_pnt_rtm: "data/pnt_rtm.csv"
  path_pnt_dam: "data/pnt_dam.csv"

  path_spdf_base_map: "data/spdf_base_map.rds"
  
  # path_sf_pnt: "data/sf_pnt.rds"
  path_sf_pnt_rtm: "data/sf_pnt_rtm.rds"
  path_sf_pnt_dam: "data/sf_pnt_dam.rds"
  
  # path_sf_poly_trim: "data/sf_poly_trim.rds"
  path_sf_poly_rtm: "data/sf_poly_rtm.rds"
  path_sf_poly_dam: "data/sf_poly_dam.rds"

production:
  
