default:
  export_data: true
  export_viz: true
  dir_data: "data"
  dir_viz: "figs"
  
  path_png_map_spp_rtm_raw: "data-raw/rtmSpp-20181115-071500.png"
  path_png_map_spp_dam_raw: "data-raw/damSpp8-2018111-071500.png"
  path_png_legend_raw: "data-raw/rtmSppLegend.png"
  
  path_kml_rtm_raw: "data-raw/rtmSppPoints-20181115-071500.kml"
  path_kml_dam_raw: "data-raw/damSpp7Points-20181115-071500.kml"
  
  path_kml_pnt_rtm: "data/kml_pnt_rtm-20181115-071500.csv"
  path_kml_pnt_dam: "data/kml_pnt_dam-20181115-071500.csv"
  
  path_color: "data/color.csv"
  
  # url_spp_rtm_raw: "http://mis.ercot.com/misapp/GetReports.do?reportTypeId=12301&reportTitle=Settlement%20Point%20Prices%20at%20Resource%20Nodes,%20Hubs%20and%20Load%20Zones&showHTMLView=&mimicKey"
  # url_spp_rtm_raw: "http://mis.ercot.com/misdownload/servlets/mirDownload?mimic_duns=&doclookupId=636106806"
  
  # url_spp_dam_raw: "http://mis.ercot.com/misapp/GetReports.do?reportTypeId=12328&reportTitle=DAM%20Hourly%20LMPs&showHTMLView=&mimicKey"
  # url_spp_dam_raw: "http://mis.ercot.com/misdownload/servlets/mirDownload?mimic_duns=&doclookupId=635949742"
  
  path_spp_rtm_raw: "data-raw/cdr.00012301.0000000000000000.20181115.071703.SPPHLZNP6905_20181115_0715.csv"
  path_spp_dam_raw: "data-raw/cdr.00012331.0000000000000000.20181114.122757.DAMSPNP4190.csv"
  
  path_pnt_rtm: "data/pnt_rtm-20181115-071500.csv"
  path_pnt_dam: "data/pnt_dam-20181115-071500.csv"
  path_pnt_rtm2dam: "data/pnt_rtm2dam-20181115-071500.csv"

  # path_spdf_base_map: "data/spdf_base_map.rds"
  path_kml_bound: "data-raw/ercot_boundary.kml"
  path_spdf_bound_poly: "data/spdf_bound_poly.rds"
  
  path_sf_pnt_rtm: "data/sf_pnt_rtm-20181115-071500.rds"
  path_sf_pnt_dam: "data/sf_pnt_dam-20181115-071500.rds"
  path_sf_pnt_rtm2dam: "data/sf_pnt_rtm2dam-20181115-071500.rds"
  
  path_sf_poly_rtm: "data/sf_poly_rtm-20181115-071500.rds"
  path_sf_poly_dam: "data/sf_poly_dam-20181115-071500.rds"
  path_sf_poly_rtm2dam: "data/sf_poly_rtm2dam-20181115-071500.rds"

production:
  
